### PR TITLE
Fixes #3: Do an HTTP redirect instead of HTML redirect

### LINKED ISSUE #3: when run on probot.glitch.me, do an HTTP redirect instead of the HTML redirect
[image](https://httpstatusdogs.com/303-see-other)

### PR DESCRIPTION
**Pull request by anshumanv**
Closes #3

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Thanks, looks great! I’ll merge it tomorrow

**Comment by anshumanv** [comment]
ping @gr2m :smile:

**Comment by gr2m** [comment]
I looked into the deployment issue with [glitch-deploy](https://github.com/glitch-tools/glitch-deploy) and it won’t be as easy as I hoped it would be to make it work, I’m sorry. 

I also talked to the Glitch folks and they asked me not to do the redirect directly, but instead show a static page first that shows some information, then have a button that people click which will then initialise the redirect.

The PR is great and I really appreciate it, but let’s put it on hold for now until I get it unblocked, ok?

**Comment by anshumanv** [comment]
Okay :)

**Comment by anshumanv** [comment]
Not sure if this is needed anymore, closing

**Pull request closed without merging**
