### PR TITLE
Add primer and tweak UI

### PR DESCRIPTION
**Pull request by bkeepers**
This adds [primer](http://primercss.io/) and adds a little sugar to the UI. What do you think?

image

Some TODOs:

- [ ] Show large preview of screenshots in step 3 on click
- [ ] Polish text

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
This looks super nice, I didn’t know about primer!

**Comment by gr2m** [comment]
I suggest we can merge it in as is (just squash the commits to follow the message conventions) and create follow up issues for the the two open tasks. This is better than what there is right now :)

**Comment by bkeepers** [comment]
> I suggest we can merge it in as is

Cool, I've got a couple tweaks to make first.

> just squash the commits to follow the message conventions

What conventions are you referring to?

**Comment by gr2m** [comment]
> Cool, I've got a couple tweaks to make first.

Cool, let me know when you are ready :)

> What conventions are you referring to?

I’ve setup semantic-release. I don’t really need to publish this to npm but I leave the automated changelogs on GitHub Releases. Here is a summary of the commit conventions:
https://github.com/hoodiehq/hoodie/blob/master/CONTRIBUTING.md#commit-message-conventions

**Comment by bkeepers** [comment]
Ok, I'm done tweaking for now. Here's the latest.


I actually have to head out of the afternoon. Feel free to squash and update this if you want to hack on it before I get back, or I can do it tonight.

image

**Comment by gr2m** [comment]
aaand it’s live https://probot.glitch.me/, love CD to Glitch :D

**Pull request merged**
